export const properties = [
    {
        id: 1,
        title: "Spacious Apartment",
        city: "New York",
        price: 2000,
        bedrooms: 2,
        bathrooms: 1,
        image:
            "https://media.istockphoto.com/id/1390233984/photo/modern-luxury-bedroom.jpg?s=612x612&w=0&k=20&c=po91poqYoQTbHUpO1LD1HcxCFZVpRG-loAMWZT7YRe4=",
    },
    {
        id: 2,
        title: "Cozy Studio",
        city: "San Francisco",
        price: 1500,
        bedrooms: 1,
        bathrooms: 1,
        image:
            "https://images.pexels.com/photos/237371/pexels-photo-237371.jpeg?cs=srgb&dl=pexels-pixabay-237371.jpg&fm=jpg",
    },
    {
        id: 3,
        title: "Luxury Villa",
        city: "Los Angeles",
        price: 5000,
        bedrooms: 4,
        bathrooms: 3,
        image: "https://mir-s3-cdn-cf.behance.net/projects/404/a486c3199518269.Y3JvcCwyMTU4LDE2ODgsMzg5LDA.jpg",
    },
    {
        id: 4,
        title: "Modern Loft",
        city: "Chicago",
        price: 1800,
        bedrooms: 3,
        bathrooms: 2,
        image: "https://img.freepik.com/free-photo/modern-luxury-bedroom-suite-bathroom_105762-1791.jpg",
    },
    {
        id: 5,
        title: "Beachfront Condo",
        city: "Miami",
        price: 3000,
        bedrooms: 2,
        bathrooms: 2,
        image: "https://img.freepik.com/free-photo/3d-rendering-modern-luxury-bedroom-suite-bathroom_105762-1936.jpg",
    },
    {
        id: 6,
        title: "Mountain Retreat",
        city: "Denver",
        price: 2500,
        bedrooms: 3,
        bathrooms: 2,
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRxnF-LLX30kMEHfWCZbZrXmck95z8pEjZ9dLWbW1Cbmlge6aJ-T5_l3jmGD6D9RW3Q3kE&usqp=CAU",
    },
    {
        id: 7,
        title: "City View Penthouse",
        city: "Seattle",
        price: 4000,
        bedrooms: 2,
        bathrooms: 1,
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ0GGVXkfDXq23ks8tMS6OuZAfBSP84TkNUt0Wn1vduHwsIrK3Gy12EvT1u_QAwr3BrAwE&usqp=CAU",
    },
    {
        id: 8,
        title: "Rural Farmhouse",
        city: "Austin",
        price: 2200,
        bedrooms: 5,
        bathrooms: 3,
        image: "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/0a/9c/48/31/martini-suite-bedroom.jpg?w=1600&h=900&s=1",
    },
    {
        id: 9,
        title: "Historic Mansion",
        city: "Boston",
        price: 6000,
        bedrooms: 6,
        bathrooms: 4,
        image: "https://www.theparkhotels.com/images/site-specific/chennai/rooms-suites-min.jpg",
    },
    {
        id: 10,
        title: "Lakefront Cottage",
        city: "Portland",
        price: 1800,
        bedrooms: 2,
        bathrooms: 1,
        image: "https://www.lottehotel.com/content/dam/lotte-hotel/lotte/yangon/accommodation/hotel/suite/royalsuite/180712-49-2000-acc-yangon-hotel.jpg.thumb.768.768.jpg",
    },
    {
        id: 11,
        title: "Ski Chalet",
        city: "Aspen",
        price: 3500,
        bedrooms: 4,
        bathrooms: 3,
        image: "https://images.pexels.com/photos/271618/pexels-photo-271618.jpeg?cs=srgb&dl=pexels-pixabay-271618.jpg&fm=jpg",
    },
    {
        id: 12,
        title: "Garden Bungalow",
        city: "San Diego",
        price: 2800,
        bedrooms: 3,
        bathrooms: 2,
        image: "https://media.istockphoto.com/id/1050564510/photo/3d-rendering-beautiful-luxury-bedroom-suite-in-hotel-with-tv.jpg?s=612x612&w=0&k=20&c=ZYEso7dgPl889aYddhY2Fj3GOyuwqliHkbbT8pjl_iM=",
    },
    {
        id: 13,
        title: "Urban Loft",
        city: "Brooklyn",
        price: 3200,
        bedrooms: 2,
        bathrooms: 1,
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTdnaGXBGmkNU25vq0naA2oceR8NXA84K54RSGPZLZO2SAoUGD9pJWdfIg8W1l58TZxnK0&usqp=CAU",
    },
    {
        id: 14,
        title: "Desert Oasis",
        city: "Phoenix",
        price: 2000,
        bedrooms: 3,
        bathrooms: 2,
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS01X28BvexXcyX1VoBd5Jv5WY-Qozqp77wLJLimsVNuvSf2O6X3D9RO9YWeY0lrVNWyLQ&usqp=CAU",
    },
    {
        id: 15,
        title: "Seaside Villa",
        city: "Malibu",
        price: 7000,
        bedrooms: 5,
        bathrooms: 3,
        image: "https://t3.ftcdn.net/jpg/06/19/00/08/360_F_619000872_AxiwLsfQqRHMkNxAbN4l5wg1MsPgBsmo.jpg",
    },
    {
        id: 16,
        title: "Countryside Chalet",
        city: "Nashville",
        price: 2400,
        bedrooms: 4,
        bathrooms: 2,
        image: "https://media.istockphoto.com/id/1318363878/photo/luxury-modern-bedroom-interior-at-night.jpg?s=612x612&w=0&k=20&c=riYXhwiUWYzqv7iA060mb14a5b7QdjZhUeqoyNoyyts=",
    },
    {
        id: 17,
        title: "Riverfront Retreat",
        city: "Portland",
        price: 2800,
        bedrooms: 3,
        bathrooms: 2,
        image: "https://static.vecteezy.com/system/resources/thumbnails/022/313/462/small_2x/modern-stylis-h-interior-of-the-hotel-room-a-large-sleeping-bed-in-dark-tones-in-daylight-generative-ai-photo.jpg",
    },
    {
        id: 18,
        title: "Art Deco Apartment",
        city: "Miami Beach",
        price: 3800,
        bedrooms: 2,
        bathrooms: 1,
        image: "https://as2.ftcdn.net/v2/jpg/05/69/05/39/1000_F_569053960_zRJqa7VdDdjoQKcKtQatRZLeCP9yCTe8.jpg",
    },
    {
        id: 19,
        title: "Tropical Hideaway",
        city: "Key West",
        price: 3200,
        bedrooms: 3,
        bathrooms: 2,
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSMwm2hKKEijweJSpQQUge8Uf748eRgt-VG87fcYz_nPSMxJQRk9pwkw8kjsttfFQVEaa4&usqp=CAU",
    },
    {
        id: 20,
        title: "Elegant Townhouse",
        city: "Charleston",
        price: 4200,
        bedrooms: 4,
        bathrooms: 3,
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQUbsmBHkp3s2fpfNRBOrYA-0VyBYEDSQ9oamq1E1I-IB0Um4X1amHERO6vZZ9k5F1AD1o&usqp=CAU",
    },
    {
        id: 21,
        title: "Lakeside Cabin",
        city: "Lake Tahoe",
        price: 2600,
        bedrooms: 2,
        bathrooms: 1,
        image: "https://media.istockphoto.com/id/1390233984/photo/modern-luxury-bedroom.jpg?s=170667a&w=is&k=20&c=e5UOHuaij7GjnCu1h6oh_syCx_i4Bn5rNTQKFvztCVo=",
    },
    {
        id: 22,
        title: "Skyline View Condo",
        city: "Chicago",
        price: 3500,
        bedrooms: 3,
        bathrooms: 2,
        image: "https://as2.ftcdn.net/v2/jpg/04/61/32/91/1000_F_461329195_hR7m55XHESGj0GpmdYeuBBFL8kkDaAyK.jpg",
    },
    {
        id: 23,
        title: "Rustic Lodge",
        city: "Jackson Hole",
        price: 3000,
        bedrooms: 4,
        bathrooms: 3,
        image: "https://imageio.forbes.com/specials-images/imageserve/652f603a91415a3d647fc207/Modern-Style-Bedroom/960x0.jpg?format=jpg&width=960",
    },
    {
        id: 24,
        title: "Modern Beach House",
        city: "Santa Monica",
        price: 4500,
        bedrooms: 3,
        bathrooms: 2,
        image: "https://static.vecteezy.com/system/resources/previews/022/313/606/non_2x/modern-stylis-h-interior-of-the-hotel-room-a-large-sleeping-bed-in-dark-tones-in-daylight-generative-ai-photo.jpg",
    },
    {
        id: 25,
        title: "Country Manor",
        city: "Atlanta",
        price: 2800,
        bedrooms: 5,
        bathrooms: 3,
        image: "https://cf.bstatic.com/xdata/images/hotel/max1024x768/187621952.jpg?k=920e6463d31fe4065b200072cc4ca463c5060526395a6bd0ec126ab3fe660ac8&o=&hp=1",
    },
    {
        id: 26,
        title: "Golf Course Estate",
        city: "Palm Springs",
        price: 5000,
        bedrooms: 4,
        bathrooms: 3,
        image: "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/15/d0/5e/dc/junior-suite-unique.jpg?w=1200&h=-1&s=1",
    },
    {
        id: 27,
        title: "Victorian Mansion",
        city: "San Francisco",
        price: 8000,
        bedrooms: 6,
        bathrooms: 4,
        image: "https://img.freepik.com/premium-photo/bedroom-interior-home-hotel-empty-apartment_839035-598988.jpg",
    },
    {
        id: 28,
        title: "Charming Cottage",
        city: "Savannah",
        price: 2200,
        bedrooms: 2,
        bathrooms: 1,
        image: "https://media.istockphoto.com/id/1732983887/photo/interior-design-of-modern-bedroom.jpg?b=1&s=612x612&w=0&k=20&c=D_8LJ0XGy8cmb1bOZWQUjQmAmStESr9agYB875jf118=",
    },
    {
        id: 29,
        title: "Sunny Beachfront Villa",
        city: "Miami Beach",
        price: 6000,
        bedrooms: 4,
        bathrooms: 3,
        image: "https://t3.ftcdn.net/jpg/04/75/76/86/360_F_475768676_wmwEVWYWNlcqaMoj4khb4GF3F0f4f7TF.jpg",
    },
    {
        id: 30,
        title: "Eco-Friendly Retreat",
        city: "Portland",
        price: 3200,
        bedrooms: 3,
        bathrooms: 2,
        image: "https://watermark.lovepik.com/photo/20211120/large/lovepik-hotel-rooms-picture_500420407.jpg",
    },
];
